name: Build DIE-engine on Windows

on:
  push:
    branches:
      - '**'  # Run on every branch commit

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Qt and build tools
        run: |
          choco install -y qt5 visualstudio2019buildtools 7zip
        shell: powershell

      - name: Build Win32 version
        run: build_win32.bat

      # Optional: Build 64-bit too
      # - name: Build Win64 version
      #   run: build_win64.bat

      - name: Upload .exe artifacts
        uses: actions/upload-artifact@v4
        with:
          name: die-exe
          path: release\*.exe
