name: Build DIE-engine on Windows

on:
  push:
    branches:
      - '**'  # Run on every branch commit

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Set up Qt and build tools
        run: |
          choco install -y qt5 visualstudio2019buildtools 7zip
          choco list --local-only
        shell: powershell

      - name: Build Win32 version
        run: build_win32.bat
        VSVARS_PATH: "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\bin\\vcvars32.bat"
        QMAKE_PATH: "C:\\Qt5.6.3\\5.6.3\\msvc2013\\bin\\qmake.exe"
        SEVENZIP_PATH: "C:\\Program Files\\7-Zip\\7z.exe"

      # Optional: Build 64-bit too
      # - name: Build Win64 version
      #   run: build_win64.bat

      - name: Upload .exe artifacts
        uses: actions/upload-artifact@v4
        with:
          name: die-exe
          path: release\*.exe
