name: Build DIE-engine on Windows

on:
  push:
    branches:
      - '**'  # Run on every branch commit

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up environment variables
        env:
          VSVARS_PATH: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\Preview\\VC\\Auxiliary\\Build\\vcvars32.bat"
          QMAKE_PATH: "C:\\Qt\\6.8.2\\msvc2022_64\\qmake.exe"
          SEVENZIP_PATH: "C:\\Program Files\\7-Zip\\7z.exe"
        run: echo Environment variables are set.

      - name: Set up Qt and build tools
        run: |
          choco install -y qt5 visualstudio2019buildtools 7zip
        shell: powershell
      
      - name: Build Win32 version
        run: build_win32.bat
        env:
          VSVARS_PATH: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\Preview\\VC\\Auxiliary\\Build\\vcvars32.bat"
          QMAKE_PATH: "C:\\Qt\\6.8.2\\msvc2022_64\\bin\\qmake.exe"
          SEVENZIP_PATH: "C:\\Program Files\\7-Zip\\7z.exe"
